
test1 = "CTCATGTGATATGTGGTATGGATGCCGGGGCCTGTTTTGGTTGTAGAGGGAGCACGAAAAACTGCGGTTTATTTTAGTTGTCTGGAATACACTGTACCGTAGCCTCCAGATTCAATCCGTCAGAAGTTGAAAATTGAAGTACCAGAGCCAGATCGCGAGATGCATAGAGAGAGACGCGACAGCATAGGGGCAACAGGACACACTGGATGGGGTACAGAGGCTCGCTCTTATATATAGTATGCGACAATGCTAATTTATTGTAGCGGCCAGTTAGCGTATCTAATCATCCTGTCAGTCTGTGTAATACAGGTGATAAGGTTTAAACTAACAGCTCACACATATGGGGGGGATTCAGCACGACATAGAATGTCGCCCCAAAAGTCTCTCCATGGAGTTTGACACGTCGCGAGATTTCCGGCCCTGCCATTGTACCTAACTACCTTAGTCCGCGCGACCTAGGACAATGTAAGTCGTTTCGTTGGTATCTGGGGGGTATTAAACGTCCTTTAGACTGTTCCGTTAGTAAGGAGCGTCCTCGGTTGGACGACCTCTACAGGGCCCTTTTCATGAGAGCTTTCCTTCAGTTACTCCGTCGCAATGCGTTCTGTGAAGGCACCGCTACTTAAACCGTGTGAAAGGAAAGCCGCGTAATTGGGTACGGAAATCTCTGAATAGTCGCGACCTTCTCTACGATATGACGGTGAGAATCGGGCCGCATCTTGGTTAAGGCAGTGGAGCAGACAAACCGGACTTTTTGAGCACACCCAACAACTGCTGCGCACAACGAGCTTTCACAACAATTGGTAGAA"
ans1 = 'TTCTACCAATTGTTGTGAAAGCTCGTTGTGCGCAGCAGTTGTTGGGTGTGCTCAAAAAGTCCGGTTTGTCTGCTCCACTGCCTTAACCAAGATGCGGCCCGATTCTCACCGTCATATCGTAGAGAAGGTCGCGACTATTCAGAGATTTCCGTACCCAATTACGCGGCTTTCCTTTCACACGGTTTAAGTAGCGGTGCCTTCACAGAACGCATTGCGACGGAGTAACTGAAGGAAAGCTCTCATGAAAAGGGCCCTGTAGAGGTCGTCCAACCGAGGACGCTCCTTACTAACGGAACAGTCTAAAGGACGTTTAATACCCCCCAGATACCAACGAAACGACTTACATTGTCCTAGGTCGCGCGGACTAAGGTAGTTAGGTACAATGGCAGGGCCGGAAATCTCGCGACGTGTCAAACTCCATGGAGAGACTTTTGGGGCGACATTCTATGTCGTGCTGAATCCCCCCCATATGTGTGAGCTGTTAGTTTAAACCTTATCACCTGTATTACACAGACTGACAGGATGATTAGATACGCTAACTGGCCGCTACAATAAATTAGCATTGTCGCATACTATATATAAGAGCGAGCCTCTGTACCCCATCCAGTGTGTCCTGTTGCCCCTATGCTGTCGCGTCTCTCTCTATGCATCTCGCGATCTGGCTCTGGTACTTCAATTTTCAACTTCTGACGGATTGAATCTGGAGGCTACGGTACAGTGTATTCCAGACAACTAAAATAAACCGCAGTTTTTCGTGCTCCCTCTACAACCAAAACAGGCCCCGGCATCCATACCACATATCACATGAG'

class Solution:

    def reverse_complement(self, input):
        map1 = {
            "A": "T",
            "T": "A",
            "G": "C",
            "C": "G",
        }
        return "".join(map(lambda x: map1[x], input[::-1]))


def test_solution():

    input1 = [(
        dict(input="AAAACCCGGT"), "ACCGGGTTTT",
    ), (
        dict(input=test1), ans1,
    )]

    for input, expect in input1:
        assert Solution().reverse_complement(**input) == expect, (input, expect)